# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clio < Formula
  desc "Clio CLI"
  homepage "https://github.com/gptscript-ai/clio"
  version "0.0.1-alpha8"

  on_macos do
    on_intel do
      url "https://github.com/gptscript-ai/clio/releases/download/v0.0.1-alpha8/clio_0.0.1-alpha8_darwin_amd64.tar.gz"
      sha256 "0a4f26664213c0cfd695e978abd00987a28ac63ccae2184cceafec5539b1734f"

      def install
        bin.install "clio"
      end
    end
    on_arm do
      url "https://github.com/gptscript-ai/clio/releases/download/v0.0.1-alpha8/clio_0.0.1-alpha8_darwin_arm64.tar.gz"
      sha256 "f86b4fafcd5cef8486d636505e266e1f3a18df74e20001dd82e3166c36770723"

      def install
        bin.install "clio"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gptscript-ai/clio/releases/download/v0.0.1-alpha8/clio_0.0.1-alpha8_linux_amd64.tar.gz"
        sha256 "a79917bef8ff09eadfbe76c1f0d85738920a2bdb287b1e0446e20ee1b45ef46e"

        def install
          bin.install "clio"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gptscript-ai/clio/releases/download/v0.0.1-alpha8/clio_0.0.1-alpha8_linux_arm64.tar.gz"
        sha256 "a72e240be92dda75cae53037393a25d19b1fc8c53b22c58bdbc5d9bcb6c2ea2a"

        def install
          bin.install "clio"
        end
      end
    end
  end
end
