# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clio < Formula
  desc "Clio CLI"
  homepage "https://github.com/gptscript-ai/clio"
  version "0.0.1-alpha6"

  on_macos do
    on_intel do
      url "https://github.com/gptscript-ai/clio/releases/download/v0.0.1-alpha6/clio_0.0.1-alpha6_darwin_amd64.tar.gz"
      sha256 "b74b088ccfd89ff6267648faaa8fd3455b6fd4db42b7449ca9f461af594139b3"

      def install
        bin.install "clio"
      end
    end
    on_arm do
      url "https://github.com/gptscript-ai/clio/releases/download/v0.0.1-alpha6/clio_0.0.1-alpha6_darwin_arm64.tar.gz"
      sha256 "edcb78aad348f200d667d52778ab3dc4c92095b7a4236f3f789d3a79275eebea"

      def install
        bin.install "clio"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gptscript-ai/clio/releases/download/v0.0.1-alpha6/clio_0.0.1-alpha6_linux_amd64.tar.gz"
        sha256 "0a78210e4a201e9e84a703294e81397898bbbf40e1212bc79e578a32f2e971b3"

        def install
          bin.install "clio"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gptscript-ai/clio/releases/download/v0.0.1-alpha6/clio_0.0.1-alpha6_linux_arm64.tar.gz"
        sha256 "9b518908a93c2b5fc21f48111b949c9fbcff92ff31a247f00c39c483f34c0566"

        def install
          bin.install "clio"
        end
      end
    end
  end
end
