# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clio < Formula
  desc "Clio CLI"
  homepage "https://github.com/gptscript-ai/clio"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/gptscript-ai/clio/releases/download/v0.1.0/clio_0.1.0_darwin_amd64.tar.gz"
      sha256 "f769700c28fbfe1b8ea98837580025fef335664ef7cd2abf8130abb35df702f3"

      def install
        bin.install "clio"
      end
    end
    on_arm do
      url "https://github.com/gptscript-ai/clio/releases/download/v0.1.0/clio_0.1.0_darwin_arm64.tar.gz"
      sha256 "6ec9d83cb3dbacc86de45d454962c792e60aad9a1ce99c4d9e5b2afe29939163"

      def install
        bin.install "clio"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gptscript-ai/clio/releases/download/v0.1.0/clio_0.1.0_linux_amd64.tar.gz"
        sha256 "8cbc8e0854bfe5a460a3c0fd07554b4c08b8d1fd7532ea3975ccfd45041ac96c"

        def install
          bin.install "clio"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gptscript-ai/clio/releases/download/v0.1.0/clio_0.1.0_linux_arm64.tar.gz"
        sha256 "a232e85242d3bcd6a43399c6e202a915db02d9fd926f86f20f268c4fe307266b"

        def install
          bin.install "clio"
        end
      end
    end
  end
end
