# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gptscript < Formula
  desc "GPTScript CLI"
  homepage "https://github.com/gptscript-ai/gptscript"
  version "0.1.4"

  on_macos do
    url "https://github.com/gptscript-ai/gptscript/releases/download/v0.1.4/gptscript-v0.1.4-macOS-universal.tar.gz"
    sha256 "3fca7c0d47bc28c0d147bbc3547662cecd1bcb664d206c2c69a9f622572b2244"

    def install
      bin.install "gptscript"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gptscript-ai/gptscript/releases/download/v0.1.4/gptscript-v0.1.4-linux-arm64.tar.gz"
      sha256 "eee2662ff8fba4aa6acbfff1b9a40f4fc3052e3748bec30cf9a85dfcb1a4912f"

      def install
        bin.install "gptscript"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gptscript-ai/gptscript/releases/download/v0.1.4/gptscript-v0.1.4-linux-amd64.tar.gz"
      sha256 "c0ff7f0c9a6d55b4d8a7f7f99b82c6e7ec596e1aef244b6df4354275ef5a0f14"

      def install
        bin.install "gptscript"
      end
    end
  end
end
