# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gptscript < Formula
  desc "GPTScript CLI"
  homepage "https://github.com/gptscript-ai/gptscript"
  version "0.9.5-rc4"

  on_macos do
    url "https://github.com/gptscript-ai/gptscript/releases/download/v0.9.5-rc4/gptscript-v0.9.5-rc4-macOS-universal.tar.gz"
    sha256 "118a629965df699bb3034e71876ef0b143d6d4a23284445fadf5f44530e29953"

    def install
      bin.install "gptscript"
      generate_completions_from_executable(bin/"gptscript", "completion")
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gptscript-ai/gptscript/releases/download/v0.9.5-rc4/gptscript-v0.9.5-rc4-linux-amd64.tar.gz"
        sha256 "1b8ff6d95694a3f73341ca04076764b1427bf8c88ddb9b041ca88d15713ac2ee"

        def install
          bin.install "gptscript"
          generate_completions_from_executable(bin/"gptscript", "completion")
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gptscript-ai/gptscript/releases/download/v0.9.5-rc4/gptscript-v0.9.5-rc4-linux-arm64.tar.gz"
        sha256 "6404380b363da0c5efcb617e2803ef31b82d6612f76647b64e8b732fdfab447b"

        def install
          bin.install "gptscript"
          generate_completions_from_executable(bin/"gptscript", "completion")
        end
      end
    end
  end
end
